# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aWsNxYJrsHWHsPOEIdzARdGeix07CXkU
"""

import numpy as np
from pylab import *
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras        import optimizers
import csv
import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

url = Path('/content/drive/MyDrive/למידה עמוקה מטלת גמר/Diamonds/data_.csv')
df1 = pd.read_csv(url)
df = pd.DataFrame(df1)
df = df.astype('float32')
df=df.to_numpy()

#shuffle data
np.random.shuffle(df)

data_x = np.array(df[:,[0,1,2,3,4,5,6,7,8,9,10]])
data_y = np.array(df[:,-1])


x_train,x_test,y_train,y_test = train_test_split(data_x,data_y,test_size=0.3,random_state=0)

#shaping the data in-order for it to be usable with tensor
data_x = np.array(x_train)
test_x = np.array(x_test)
data_y = np.array(y_train).reshape((-1,1))
test_y = np.array(y_test).reshape((-1,1))

ml = LinearRegression()
ml.fit(data_x,data_y)
y_pred = ml.predict(test_x)
print(y_pred)

r2_score(y_test, y_pred)